name: dvbconf-for-isdb

on:
  push:
    paths:
      - "src/dvbconf-for-isdb/**"

  workflow_dispatch:

permissions:
  contents: read
  packages: write
  actions: read
  security-events: write

jobs:
  build:
    uses: SlashNephy/actions/.github/workflows/build-docker-image.yml@cf12e2d382df42d9fcfc4ee94f901661d8255d19 # v0.0.7
    with:
      image-name: ghcr.io/slashnephy/dvbconf-for-isdb
      context: src/dvbconf-for-isdb
