name: 'Check .github/workflows/*.yml'

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'

  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'

  workflow_dispatch:

jobs:
  lint:
    uses: SlashNephy/.github/.github/workflows/actionlint.yml@2b64691f87d64d627f89946fb6f21169ddffc8b0 # master
    permissions:
      contents: 'read'
      pull-requests: 'write'
