name: 'Check Dockerfile'

on:
  push:
    branches:
      - 'master'
    paths:
      - '**/Dockerfile'

  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '**/Dockerfile'

  workflow_dispatch:

jobs:
  lint:
    uses: SlashNephy/.github/.github/workflows/hadolint.yml@2b64691f87d64d627f89946fb6f21169ddffc8b0 # master
    permissions:
      contents: 'read'
      pull-requests: 'write'
